apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: weblogic
resources:
  - ../../namespace.yaml
  - ../../pv.yaml
  - ../../pvc-weblogic-home.yaml
  - ../../gen-ssh-keys-config.yaml
  - ../../weblogic-authorized-keys.yaml
  - ../../services-clusterip.yaml
  - ../../services-nodeports.yaml
  - ../../deploy-test-db.yaml
  - deploy-wls-admin.yaml
  - deploy-wls-managed-1.yaml
  - deploy-wls-managed-2.yaml
  - deploy-wls-managed-3.yaml
patches:
  - path: patch-pvc-storageclass.yaml

