apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../pv.yaml
  - ../../pvc-weblogic-home.yaml
  - ../../services-clusterip.yaml
  - ../../deploy-test-db.yaml
  - deploy-wls-admin.yaml
  - deploy-wls-managed-1.yaml
  - deploy-wls-managed-2.yaml
  - deploy-wls-managed-3.yaml
patches:
  - path: patch-pvc-storageclass.yaml

# Image-Override: Kustomize ersetzt das Image in deploy-test-db.yaml automatisch
# Du hast postgres_15:1.0 in Harbor, deshalb:
images:
  - name: postgres
    newName: "DEIN_HARBOR_HOST/weblogic/postgres_15"
    newTag: "1.0"
# Beispiel: newName: harbor.example.com/weblogic/postgres_15

