apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-db
  namespace: weblogic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-db
  template:
    metadata:
      labels:
        app: test-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: weblogic
        - name: POSTGRES_PASSWORD
          value: weblogic
        - name: POSTGRES_DB
          value: fmw
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}

