apiVersion: apps/v1
kind: Deployment
metadata:
  name: wls-managed-1
  namespace: weblogic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wls-managed-1
  template:
    metadata:
      labels:
        app: wls-managed-1
    spec:
      volumes:
      - name: ssh-keys
        emptyDir: {}
      - name: home
        emptyDir: {}
      - name: domain-home
        persistentVolumeClaim:
          claimName: pvc-weblogic-home
      - name: gen-ssh-keys-script
        configMap:
          name: gen-ssh-keys-script
          defaultMode: 0755

      initContainers:
      - name: gen-ssh-keys
        image: wls-dev:1.3
        command:
          - /bin/sh
          - -c
          - /scripts/gen-ssh-keys.sh
        volumeMounts:
          - name: ssh-keys
            mountPath: /etc/ssh
          - name: home
            mountPath: /home/docker
          - name: gen-ssh-keys-script
            mountPath: /scripts
            readOnly: true

      containers:
      - name: wls-managed
        image: wls-dev:1.3
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 22
        volumeMounts:
        - name: ssh-keys
          mountPath: /etc/ssh
        - name: home
          mountPath: /home/docker
        - name: domain-home
          mountPath: /u01/domains

