apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-weblogic-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/weblogic/pv-home
    type: DirectoryOrCreate

