apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-weblogic-home
  namespace: weblogic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

