apiVersion: v1
kind: Service
metadata:
  name: wls-admin-ssh
  namespace: weblogic
spec:
  selector:
    app: wls-admin
  ports:
  - port: 22
    targetPort: 22
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: wls-managed-1-ssh
  namespace: weblogic
spec:
  selector:
    app: wls-managed-1
  ports:
  - port: 22
    targetPort: 22
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: wls-managed-2-ssh
  namespace: weblogic
spec:
  selector:
    app: wls-managed-2
  ports:
  - port: 22
    targetPort: 22
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: test-db
  namespace: weblogic
spec:
  selector:
    app: test-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

