apiVersion: v1
data:
  id_ed25519_docker.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKdp/XDFuXTy8xjyvpb2Fr1Lf6NbDiC3QDpA8kQH0tkd docker@flowops
kind: ConfigMap
metadata:
  name: weblogic-authorized-keys
  namespace: weblogic
