#!/usr/bin/env python3
"""
Generate inventory.yaml for Ansible kubectl-exec access to WLS pods.

No SSH, no node access required.
Ansible uses the kubernetes.core.kubectl connection plugin,
which shells into pods via 'kubectl exec'.

Usage examples:
  ./scripts/generate_inventory_k8s.py
  KC_CMD="kubectl --context prod-cluster" ./scripts/generate_inventory_k8s.py -n wl
  ./scripts/generate_inventory_k8s.py --context prod-cluster --namespace wl

Environment variables:
  KC_CMD           kubectl command (default: kubectl)
  WL_NAMESPACE     namespace (default: wl)
  KC_CONTEXT       kubectl context (optional)
  KUBECONFIG       kubeconfig path (optional)
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import List, Optional


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_FILE = REPO_ROOT / "inventory.yaml"
DEFAULT_KC_CMD = "kubectl"

# (label-selector, inventory-host-name, container-name)
WLS_POD_MAP: List[tuple] = [
    ("app=wls-admin",     "wls-admin",     "wls-admin"),
    ("app=wls-managed-1", "wls-managed-1", "wls-managed"),
    ("app=wls-managed-2", "wls-managed-2", "wls-managed"),
    ("app=wls-managed-3", "wls-managed-3", "wls-managed"),
]


def run_json(kc_args: List[str], extra: List[str]) -> dict:
    cmd = kc_args + extra + ["-o", "json"]
    try:
        out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, text=True)
        return json.loads(out)
    except subprocess.CalledProcessError as exc:
        print(f"Command failed: {' '.join(cmd)}\n{exc.output}", file=sys.stderr)
        raise
    except FileNotFoundError:
        print(f"kubectl binary not found: {cmd[0]}", file=sys.stderr)
        raise


def find_running_pod(kc_args: List[str], namespace: str, label_selector: str) -> Optional[str]:
    """Return name of first Running pod matching the label selector, or None."""
    cmd = kc_args + [
        "get", "pods",
        "-n", namespace,
        "-l", label_selector,
        "--field-selector=status.phase=Running",
        "-o", "jsonpath={.items[0].metadata.name}",
    ]
    try:
        out = subprocess.check_output(cmd, stderr=subprocess.DEVNULL, text=True).strip()
        return out if out else None
    except subprocess.CalledProcessError:
        return None


def write_inventory(
    out_file: Path,
    namespace: str,
    kc_context: Optional[str],
    kc_kubeconfig: Optional[str],
    pods: List[tuple],  # (inv_name, container, pod_name_or_None)
) -> None:
    with out_file.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by scripts/generate_inventory_k8s.py\n")
        fh.write("# Ansible access via kubectl exec (no SSH required).\n")
        fh.write("# Requires: kubernetes.core collection.\n")
        fh.write("#   ansible-galaxy collection install kubernetes.core\n\n")
        fh.write("all:\n")
        fh.write("  children:\n")
        fh.write("    weblogic_pods:\n")
        fh.write("      vars:\n")
        fh.write("        ansible_connection: kubernetes.core.kubectl\n")
        fh.write(f"        ansible_kubectl_namespace: {namespace}\n")
        if kc_context:
            fh.write(f"        ansible_kubectl_context: {kc_context}\n")
        if kc_kubeconfig:
            fh.write(f"        ansible_kubectl_kubeconfig: {kc_kubeconfig}\n")
        fh.write("      hosts:\n")

        for inv_name, container, pod_name in pods:
            fh.write(f"        {inv_name}:\n")
            fh.write(f"          ansible_kubectl_container: {container}\n")
            if pod_name:
                fh.write(f"          ansible_kubectl_pod: {pod_name}\n")
            else:
                fh.write(f"          ansible_kubectl_pod: # pod not running – re-run after deploy\n")

        fh.write("\n# Tip: re-run this script after pod restarts to refresh pod names.\n")
        fh.write("# group_vars/weblogic_pods.yml can hold shared variables.\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Ansible kubectl-exec inventory for WLS pods (no SSH)"
    )
    parser.add_argument(
        "-n", "--namespace",
        default=os.environ.get("WL_NAMESPACE", "wl"),
        help="Kubernetes namespace (default: wl)",
    )
    parser.add_argument(
        "-o", "--out-file",
        default=str(DEFAULT_OUT_FILE),
        help="Output inventory path (default: <repo>/inventory.yaml)",
    )
    parser.add_argument(
        "--kc-cmd",
        default=os.environ.get("KC_CMD", DEFAULT_KC_CMD),
        help="kubectl command (default: kubectl)",
    )
    parser.add_argument(
        "--context",
        default=os.environ.get("KC_CONTEXT"),
        help="kubectl context (written into inventory vars; optional)",
    )
    parser.add_argument(
        "--kubeconfig",
        default=os.environ.get("KUBECONFIG"),
        help="kubeconfig path (written into inventory vars; optional)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    out_file = Path(args.out_file).expanduser().resolve()
    kc_args = shlex.split(args.kc_cmd)

    if args.context and "--context" not in args.kc_cmd:
        kc_args += ["--context", args.context]

    print(f"Namespace : {args.namespace}")
    print(f"kubectl   : {' '.join(kc_args)}")
    print()

    # Verify cluster is reachable
    try:
        run_json(kc_args, ["get", "pods", "-n", args.namespace])
    except Exception:
        print("Could not reach cluster. Check your kubectl context.", file=sys.stderr)
        return 1

    pods = []
    for label_selector, inv_name, container in WLS_POD_MAP:
        pod_name = find_running_pod(kc_args, args.namespace, label_selector)
        status = pod_name if pod_name else "(not running)"
        print(f"  {inv_name:<20} -> {status}")
        pods.append((inv_name, container, pod_name))

    out_file.parent.mkdir(parents=True, exist_ok=True)
    write_inventory(
        out_file=out_file,
        namespace=args.namespace,
        kc_context=args.context,
        kc_kubeconfig=args.kubeconfig,
        pods=pods,
    )

    print(f"\nWrote inventory to {out_file}")
    running = sum(1 for _, _, p in pods if p)
    print(f"Running pods: {running}/{len(pods)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

