#!/usr/bin/env bash
set -euo pipefail

# Generate inventory.yaml for Ansible kubectl-exec access to WLS pods.
# No SSH, no node access required.
# Ansible uses kubernetes.core.kubectl connection plugin (kubectl exec).
#
# Usage examples:
#   ./scripts/generate_inventory_k8s.sh
#   KC_CMD="kubectl --context prod" ./scripts/generate_inventory_k8s.sh -n wl
#   ./scripts/generate_inventory_k8s.sh --context prod --namespace wl

NAMESPACE="${WL_NAMESPACE:-wl}"
OUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/inventory.yaml"
KC_CMD="${KC_CMD:-kubectl}"
KC_CONTEXT="${KC_CONTEXT:-}"
KC_KUBECONFIG="${KUBECONFIG:-}"

usage() {
  cat <<'EOF'
Usage: scripts/generate_inventory_k8s.sh [options]

Options:
  -n, --namespace <ns>       Kubernetes namespace (default: wl)
  -o, --out-file <path>      Output file (default: <repo>/inventory.yaml)
      --kc-cmd <cmd>         kubectl command (default: $KC_CMD or kubectl)
      --context <ctx>        kubectl context (written to inventory; optional)
      --kubeconfig <path>    kubeconfig path (written to inventory; optional)
  -h, --help                 Show this help

Environment variables:
  KC_CMD, WL_NAMESPACE, KC_CONTEXT, KUBECONFIG
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -n|--namespace)   NAMESPACE="$2";     shift 2 ;;
    -o|--out-file)    OUT_FILE="$2";      shift 2 ;;
    --kc-cmd)         KC_CMD="$2";        shift 2 ;;
    --context)        KC_CONTEXT="$2";    shift 2 ;;
    --kubeconfig)     KC_KUBECONFIG="$2"; shift 2 ;;
    -h|--help)        usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

# Inject --context into KC_CMD if given
if [ -n "$KC_CONTEXT" ] && ! echo "$KC_CMD" | grep -q -- '--context'; then
  KC_CMD="$KC_CMD --context $KC_CONTEXT"
fi

read -r -a KC <<<"$KC_CMD"

run_kc() {
  "${KC[@]}" "$@"
}

find_running_pod() {
  local label="$1"
  run_kc get pods -n "$NAMESPACE" \
    -l "$label" \
    --field-selector=status.phase=Running \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true
}

echo "Namespace : $NAMESPACE"
echo "kubectl   : $KC_CMD"
echo

# Verify cluster is reachable
if ! run_kc get pods -n "$NAMESPACE" -o name >/dev/null 2>&1; then
  echo "Error: Cannot reach cluster. Check kubectl context." >&2
  exit 1
fi

# Resolve pod names per label
ADMIN_POD="$(find_running_pod 'app=wls-admin')"
M1_POD="$(find_running_pod 'app=wls-managed-1')"
M2_POD="$(find_running_pod 'app=wls-managed-2')"
M3_POD="$(find_running_pod 'app=wls-managed-3')"

for name in wls-admin wls-managed-1 wls-managed-2 wls-managed-3; do
  varname="${name//-/_}_pod"
  varname="${varname^^}"
  val="${!varname:-}"
  printf "  %-20s -> %s\n" "$name" "${val:-(not running)}"
done

mkdir -p "$(dirname "$OUT_FILE")"

{
  echo "# Generated by scripts/generate_inventory_k8s.sh"
  echo "# Ansible access via kubectl exec (no SSH required)."
  echo "# Requires: kubernetes.core collection."
  echo "#   ansible-galaxy collection install kubernetes.core"
  echo
  echo "all:"
  echo "  children:"
  echo "    weblogic_pods:"
  echo "      vars:"
  echo "        ansible_connection: kubernetes.core.kubectl"
  echo "        ansible_kubectl_namespace: ${NAMESPACE}"
  [ -n "$KC_CONTEXT" ]    && echo "        ansible_kubectl_context: ${KC_CONTEXT}"
  [ -n "$KC_KUBECONFIG" ] && echo "        ansible_kubectl_kubeconfig: ${KC_KUBECONFIG}"
  echo "      hosts:"

  echo "        wls-admin:"
  echo "          ansible_kubectl_container: wls-admin"
  if [ -n "$ADMIN_POD" ]; then
    echo "          ansible_kubectl_pod: ${ADMIN_POD}"
  else
    echo "          ansible_kubectl_pod: # pod not running – re-run after deploy"
  fi

  echo "        wls-managed-1:"
  echo "          ansible_kubectl_container: wls-managed"
  if [ -n "$M1_POD" ]; then
    echo "          ansible_kubectl_pod: ${M1_POD}"
  else
    echo "          ansible_kubectl_pod: # pod not running – re-run after deploy"
  fi

  echo "        wls-managed-2:"
  echo "          ansible_kubectl_container: wls-managed"
  if [ -n "$M2_POD" ]; then
    echo "          ansible_kubectl_pod: ${M2_POD}"
  else
    echo "          ansible_kubectl_pod: # pod not running – re-run after deploy"
  fi

  echo "        wls-managed-3:"
  echo "          ansible_kubectl_container: wls-managed"
  if [ -n "$M3_POD" ]; then
    echo "          ansible_kubectl_pod: ${M3_POD}"
  else
    echo "          ansible_kubectl_pod: # pod not running – re-run after deploy"
  fi

  echo
  echo "# Tip: re-run this script after pod restarts to refresh pod names."
  echo "# group_vars/weblogic_pods.yml can hold shared variables."
} > "$OUT_FILE"

running=0
[ -n "$ADMIN_POD" ] && running=$((running+1))
[ -n "$M1_POD" ]    && running=$((running+1))
[ -n "$M2_POD" ]    && running=$((running+1))
[ -n "$M3_POD" ]    && running=$((running+1))

echo
echo "Wrote inventory to $OUT_FILE"
echo "Running pods: ${running}/4"


NAMESPACE="wl"
OUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/inventory.yaml"
KC_CMD="${KC_CMD:-kubectl}"
KEY_PATH="${ANSIBLE_SSH_KEY:-${HOME}/.ssh/id_ed25519}"
SSH_USER="${ANSIBLE_SSH_USER:-docker}"
NODEPORT_HOST="${ANSIBLE_NODEPORT_HOST:-}"

usage() {
  cat <<'EOF'
Usage: scripts/generate_inventory_k8s.sh [options]

Options:
  -n, --namespace <ns>       Namespace for NodePort services (default: wl)
  -o, --out-file <path>      Output file (default: <repo>/inventory.yaml)
      --kc-cmd <cmd>         kubectl command (default: $KC_CMD or kubectl)
      --ssh-key <path>       SSH private key path (default: ~/.ssh/id_ed25519)
      --ssh-user <user>      SSH user (default: docker)
      --nodeport-host <ip>   Override ansible_host for weblogic_ssh entries
  -h, --help                 Show this help
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    -n|--namespace)
      NAMESPACE="$2"
      shift 2
      ;;
    -o|--out-file)
      OUT_FILE="$2"
      shift 2
      ;;
    --kc-cmd)
      KC_CMD="$2"
      shift 2
      ;;
    --ssh-key)
      KEY_PATH="$2"
      shift 2
      ;;
    --ssh-user)
      SSH_USER="$2"
      shift 2
      ;;
    --nodeport-host)
      NODEPORT_HOST="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

# Split KC_CMD into an argv array (works for normal commands like 'kubectl --context X').
read -r -a KC <<<"$KC_CMD"

run_kc() {
  "${KC[@]}" "$@"
}

pick_ip_from_addresses() {
  # Input format: "InternalIP=10.0.0.5,Hostname=node1,..."
  local addresses="$1"
  local item type value

  IFS=',' read -r -a parts <<<"$addresses"

  for item in "${parts[@]}"; do
    type="${item%%=*}"
    value="${item#*=}"
    if [ "$type" = "InternalIP" ] && [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done

  for item in "${parts[@]}"; do
    type="${item%%=*}"
    value="${item#*=}"
    if [ "$type" = "ExternalIP" ] && [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done

  for item in "${parts[@]}"; do
    type="${item%%=*}"
    value="${item#*=}"
    if [ "$type" = "Hostname" ] && [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done

  return 1
}

get_nodeport() {
  local svc_name="$1"
  run_kc -n "$NAMESPACE" get svc "$svc_name" -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || true
}

echo "Reading Kubernetes nodes via: $KC_CMD"
NODE_LINES="$(run_kc get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"|"}{.metadata.labels.node-role\.kubernetes\.io/control-plane}{"|"}{.metadata.labels.node-role\.kubernetes\.io/master}{"|"}{range .status.addresses[*]}{.type}{"="}{.address}{","}{end}{"\n"}{end}')"

if [ -z "$NODE_LINES" ]; then
  echo "No nodes returned by kubectl." >&2
  exit 1
fi

CONTROL_TMP="$(mktemp)"
WORKER_TMP="$(mktemp)"
trap 'rm -f "$CONTROL_TMP" "$WORKER_TMP"' EXIT

FIRST_CONTROL_IP=""
FIRST_WORKER_IP=""

while IFS='|' read -r name cp_label master_label addresses; do
  [ -z "$name" ] && continue

  if ! ip="$(pick_ip_from_addresses "$addresses")"; then
    continue
  fi

  if [ -n "$cp_label" ] || [ -n "$master_label" ]; then
    printf '%s|%s\n' "$name" "$ip" >> "$CONTROL_TMP"
    [ -z "$FIRST_CONTROL_IP" ] && FIRST_CONTROL_IP="$ip"
  else
    printf '%s|%s\n' "$name" "$ip" >> "$WORKER_TMP"
    [ -z "$FIRST_WORKER_IP" ] && FIRST_WORKER_IP="$ip"
  fi
done <<< "$NODE_LINES"

if [ ! -s "$CONTROL_TMP" ] && [ ! -s "$WORKER_TMP" ]; then
  echo "No usable nodes found (missing node IPs)." >&2
  exit 1
fi

if [ -z "$NODEPORT_HOST" ]; then
  if [ -n "$FIRST_CONTROL_IP" ]; then
    NODEPORT_HOST="$FIRST_CONTROL_IP"
  else
    NODEPORT_HOST="$FIRST_WORKER_IP"
  fi
fi

if [ -z "$NODEPORT_HOST" ]; then
  echo "Could not determine nodeport host IP; use --nodeport-host." >&2
  exit 1
fi

ADMIN_PORT="$(get_nodeport wls-admin-ssh-nodeport)"
M1_PORT="$(get_nodeport wls-managed-1-ssh-nodeport)"
M2_PORT="$(get_nodeport wls-managed-2-ssh-nodeport)"

mkdir -p "$(dirname "$OUT_FILE")"

{
  echo "all:"
  echo "  children:"
  echo "    control:"
  echo "      hosts:"
  if [ -s "$CONTROL_TMP" ]; then
    while IFS='|' read -r name ip; do
      echo "        ${name}:"
      echo "          ansible_host: ${ip}"
      echo "          ansible_user: ${SSH_USER}"
      echo "          ansible_ssh_private_key_file: ${KEY_PATH}"
    done < "$CONTROL_TMP"
  else
    echo "        # no hosts detected"
  fi

  echo "    workers:"
  echo "      hosts:"
  if [ -s "$WORKER_TMP" ]; then
    while IFS='|' read -r name ip; do
      echo "        ${name}:"
      echo "          ansible_host: ${ip}"
      echo "          ansible_user: ${SSH_USER}"
      echo "          ansible_ssh_private_key_file: ${KEY_PATH}"
    done < "$WORKER_TMP"
  else
    echo "        # no hosts detected"
  fi

  echo "    weblogic_ssh:"
  echo "      hosts:"
  wrote_np=0
  if [ -n "$ADMIN_PORT" ]; then
    echo "        wls-admin-node:"
    echo "          ansible_host: ${NODEPORT_HOST}"
    echo "          ansible_port: ${ADMIN_PORT}"
    echo "          ansible_user: ${SSH_USER}"
    echo "          ansible_ssh_private_key_file: ${KEY_PATH}"
    wrote_np=1
  fi
  if [ -n "$M1_PORT" ]; then
    echo "        wls-managed-1-node:"
    echo "          ansible_host: ${NODEPORT_HOST}"
    echo "          ansible_port: ${M1_PORT}"
    echo "          ansible_user: ${SSH_USER}"
    echo "          ansible_ssh_private_key_file: ${KEY_PATH}"
    wrote_np=1
  fi
  if [ -n "$M2_PORT" ]; then
    echo "        wls-managed-2-node:"
    echo "          ansible_host: ${NODEPORT_HOST}"
    echo "          ansible_port: ${M2_PORT}"
    echo "          ansible_user: ${SSH_USER}"
    echo "          ansible_ssh_private_key_file: ${KEY_PATH}"
    wrote_np=1
  fi
  if [ "$wrote_np" -eq 0 ]; then
    echo "        # no matching NodePort services found in namespace"
  fi

  echo
  echo "# You can add group_vars under group_vars/ directory or edit this file to add vars."
} > "$OUT_FILE"

control_count=$(wc -l < "$CONTROL_TMP" | tr -d ' ')
worker_count=$(wc -l < "$WORKER_TMP" | tr -d ' ')
nodeport_count=0
[ -n "$ADMIN_PORT" ] && nodeport_count=$((nodeport_count + 1))
[ -n "$M1_PORT" ] && nodeport_count=$((nodeport_count + 1))
[ -n "$M2_PORT" ] && nodeport_count=$((nodeport_count + 1))

echo "Wrote inventory to $OUT_FILE"
echo "control=${control_count} workers=${worker_count} nodeport_services=${nodeport_count}"
