#!/usr/bin/env bash
# Render a usable WebLogic operator manifest into k8s/operator.yaml for v4.3.9.
#
# This combines:
#   1) the CRDs (domain + cluster)
#   2) the operator Helm chart rendered with hosted-cluster-friendly values
#
# Usage:
#   ./scripts/render_weblogic_operator_manifest.sh [version]
#
# Examples:
#   ./scripts/render_weblogic_operator_manifest.sh
#   ./scripts/render_weblogic_operator_manifest.sh v4.3.9

set -euo pipefail

VERSION="${1:-v4.3.9}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/k8s/operator.yaml"
VALUES_FILE="${REPO_ROOT}/k8s/operator-hosted-values.yaml"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: '$1' is required but not installed." >&2
    exit 1
  }
}

need curl
need git
need helm

if [[ ! -f "${VALUES_FILE}" ]]; then
  echo "Error: missing values file ${VALUES_FILE}" >&2
  exit 1
fi

if [[ -f "${OUTPUT_FILE}" && ! -s "${OUTPUT_FILE}" ]]; then
  echo "Warning: ${OUTPUT_FILE} exists but is empty; it will be overwritten." >&2
fi

echo "Cloning WebLogic Kubernetes Operator ${VERSION}..."
git clone --depth 1 --branch "${VERSION}" https://github.com/oracle/weblogic-kubernetes-operator.git "${TMP_DIR}/weblogic-kubernetes-operator" >/dev/null

CHART_DIR="${TMP_DIR}/weblogic-kubernetes-operator/kubernetes/charts/weblogic-operator"
CRD_DOMAIN_URL="https://raw.githubusercontent.com/oracle/weblogic-kubernetes-operator/${VERSION}/kubernetes/crd/domain-crd.yaml"
CRD_CLUSTER_URL="https://raw.githubusercontent.com/oracle/weblogic-kubernetes-operator/${VERSION}/kubernetes/crd/cluster-crd.yaml"

helm template sample-weblogic-operator "${CHART_DIR}" \
  --namespace weblogic-operator \
  --values "${VALUES_FILE}" \
  > "${TMP_DIR}/operator-rendered.yaml"

curl -fsSL "${CRD_DOMAIN_URL}" -o "${TMP_DIR}/domain-crd.yaml"
curl -fsSL "${CRD_CLUSTER_URL}" -o "${TMP_DIR}/cluster-crd.yaml"

{
  echo "# Generated by scripts/render_weblogic_operator_manifest.sh"
  echo "# Source operator tag: ${VERSION}"
  echo
  cat "${TMP_DIR}/domain-crd.yaml"
  echo "---"
  cat "${TMP_DIR}/cluster-crd.yaml"
  echo "---"
  cat "${TMP_DIR}/operator-rendered.yaml"
} > "${OUTPUT_FILE}"

echo "Wrote ${OUTPUT_FILE}"
echo ""
echo "Next steps:"
echo "  kubectl apply -f ${OUTPUT_FILE}"
echo "  kubectl get crd domains.weblogic.oracle"
echo "  kubectl get crd clusters.weblogic.oracle"


